import Link from 'next/link';
import styles from './notes.module.css';
import CreateNote from './CreateNote';

//Next13 feature: Components are server components by default
//They get rendered in the server, therefore
//We can do data fetching directly inside of them with ASYNC / AWAIT
async function getNotes() { 
  const res = await fetch('http://127.0.0.1:8090/api/collections/notes/records?page=1&perPage=30', 
  { cache: 'no-store' }); // Refresh items from the server on every request
  const data = await res.json();
  return data?.items as any[];
}

export default async function NotesPage() {
  const notes = await getNotes();

  return(
    <main className={styles.main}>
      <div>
        <h1>Notes</h1>
        <div className={styles.grid}>
          {notes?.map((note) => {
            return <Note key={note.id} note={note} />;
          })}
        </div>
      </div>

      <CreateNote />
    </main>
  );
}

//Note compoment
function Note({ note }: any) {
  const { id, title, content, created, updated } = note || {};

  //Random ID generated by PocketBase | A dynamic route needs to be created to handle that
  return (
    <Link href={`/notes/${id}`}> 
      <div className={styles.note}>
        <h2>{title}</h2>
        <h5>{content}</h5>
        <p>{created}</p>
        <p>{updated}</p>
      </div>
    </Link>
  );
}